apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-db-pvc
spec:
  storageClassName: do-block-storage-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
