name: ecommerce-backend-depl

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
    
      - name: Build the Docker image
        run: |
          cd backend
          docker build -t elberthomax/ecommerce .
      
      - name: Login into dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push image to dockerhub
        run: docker push elberthomax/ecommerce
      
      # Download and Install IBM Cloud CLI
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_CLUSTER_NAME }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
      - run: kubectl rollout restart deployment ecommerce-depl
