name: ecommerce-infra-config

on:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/k8/**'
      - 'infra/prod/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      # Download and Install Azure
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_CLUSTER_NAME }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
      - run: kubectl apply -f infra/k8
      - run: kubectl apply -f infra/prod
